### ISSUE TITLE
Installation instructions are misleading

### ISSUE THREAD

**Issue by joshtemple** [singer-io/knots#158]
The README states that you can download a .dmg file and use that to install this app, but the link provided just downloads a zip of the repo. How can I actually install this without having to package it myself?

**Comment by rflprr** [comment]
@joshtemple Thanks for being interested in KNOTS and reporting this issue. Until today, no version of the app had been officially released. Today we released 1.0.0-beta and you can get it in here: https://github.com/singer-io/knots/releases
