### ISSUE TITLE
Facebook sdk deprecated

### ISSUE THREAD

**Issue by MaloRchrd** [singer-io/knots#188]
I cannot make tap-facebook to work cause sdk is deprecated needs to be updated to 3.2. (C.F: screenshot) 

<img width="1011" alt="capture d ecran 2019-01-14 a 14 03 06" src="https://user-images.githubusercontent.com/17042850/51098444-5c108380-1805-11e9-8ee8-94732ebcb64b.png">

**Comment by kndungu** [comment]
Thanks for reporting the issue @MaloRchrd.

Unfortunately this lies in tap-facebook's domain and not KNOTS'. Please consider opening the issue there.

Facebook updated the `facebook_business` API and deprecated the previous one, unfortunaely tap-facebook still uses the deprecated version:

https://github.com/singer-io/tap-facebook/blob/7b5aa2a61770e22777dd6bcee45a8177ebe39c5e/setup.py#L15

There are compatibility issues to deal with which I suspect is the reason the tap-facebook team has taken so long updating the tap to the latest API.

However if you created your app before v3.1 came out you can specify the API version to use on the app settings:

<img width="1184" alt="specify-api" src="https://user-images.githubusercontent.com/17295379/51337599-947bc000-1a98-11e9-973c-90b65b0a8923.png">
