### ISSUE TITLE
KNOTS not running "Wake up, Docker"

### ISSUE THREAD

**Issue by XRyu** [singer-io/knots#189]
Docker Desktop for Windows is installed, when starting KNOTS it only says "Wake up Docker".
When opening a commandline and running "docker -v" it says "Docker version 18.09.3, build 774a1f4"
What am i doing wrong?

Any ideas? :)

**Comment by kndungu** [comment]
Hello @XRyu 

This warning appears when Docker is installed but not running. This can be confirmed by trying to run a command that requires Docker to be running e.g. `docker volume ls`

You can start docker from the start menu, once running an icon will appear on the taskbar.

**Comment by XRyu** [comment]
Thank you :) now it works. docker itself was running, but had a problem because of some bugs with CA-certs. this was because i switched from "Docker Toolbox for Windows" to the newer "Docker Desktop".
I had to uninstall Docker first, clean the ~User\.docker files and delete the DOCKER_* Environment Variables first.
